// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The datasource URL is defined in prisma/schema.prisma. It is intentionally not
// overridden here so `prisma generate` works without a DATABASE_URL env var
// (e.g. during `npm install` / Vercel builds).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
